### ISSUE TITLE
Error with get_coreclr

### ISSUE THREAD

**Issue by ghost** [saivineeth100/Python_Tally#1]
I am getting the following error.

   rt = get_coreclr("TallyConnector.json") #Json we created earlier
TypeError: get_coreclr() takes 0 positional arguments but 1 was given

Can you help me with this issue?

**Comment by saivineeth100** [comment]
Now there is Stable release in Python. Net and they changed their API to load .Net runtime
Now we don't require any config file simply call` load("coreclr")`
![image](https://user-images.githubusercontent.com/64919520/211793999-b36c3f1f-4118-4744-86b1-0c9ab62cfd35.png)

I also updated this [repo ](https://github.com/saivineeth100/Python_Tally/blob/main/Tally.ipynb)with sample code that supports latest version of tally connector and Python .Net, you can use that as starting Point
